-- BrightCare Derby integration schema.
-- Run this once against jdbc:derby://localhost:1527/BRIGHTCARE_DB.
-- Reports are generated dynamically, so no REPORT table is created.

CREATE TABLE USER_ACCOUNT (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT ck_user_account_role CHECK (role IN ('ADMIN', 'DOCTOR', 'RECEPTIONIST', 'PATIENT')),
    CONSTRAINT ck_user_account_status CHECK (status IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE PATIENT (
    patient_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    ic_passport_no VARCHAR(30) NOT NULL UNIQUE,
    contact_number VARCHAR(20) NOT NULL,
    medical_record_id VARCHAR(30) NOT NULL UNIQUE,
    CONSTRAINT fk_patient_user_account FOREIGN KEY (user_id)
        REFERENCES USER_ACCOUNT (user_id)
);

CREATE TABLE DOCTOR (
    doctor_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT,
    name VARCHAR(100) NOT NULL,
    specialization VARCHAR(100) NOT NULL,
    contact_number VARCHAR(20) NOT NULL,
    CONSTRAINT fk_doctor_user_account FOREIGN KEY (user_id)
        REFERENCES USER_ACCOUNT (user_id)
);

CREATE TABLE APPOINTMENT (
    appointment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INT NOT NULL,
    doctor_id INT NOT NULL,
    appointment_date DATE NOT NULL,
    appointment_time TIME NOT NULL,
    status VARCHAR(20) NOT NULL,
    reason VARCHAR(255),
    CONSTRAINT fk_appointment_patient FOREIGN KEY (patient_id)
        REFERENCES PATIENT (patient_id),
    CONSTRAINT fk_appointment_doctor FOREIGN KEY (doctor_id)
        REFERENCES DOCTOR (doctor_id),
    CONSTRAINT ck_appointment_status CHECK (status IN ('BOOKED', 'CANCELLED', 'COMPLETED'))
);

CREATE TABLE CONSULTATION_NOTE (
    note_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id INT NOT NULL,
    doctor_id INT NOT NULL,
    notes CLOB,
    diagnosis CLOB,
    prescription CLOB,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_consultation_appointment FOREIGN KEY (appointment_id)
        REFERENCES APPOINTMENT (appointment_id),
    CONSTRAINT fk_consultation_doctor FOREIGN KEY (doctor_id)
        REFERENCES DOCTOR (doctor_id)
);

CREATE INDEX idx_patient_user_id ON PATIENT (user_id);
CREATE INDEX idx_doctor_user_id ON DOCTOR (user_id);
CREATE INDEX idx_appointment_patient_id ON APPOINTMENT (patient_id);
CREATE INDEX idx_appointment_doctor_date ON APPOINTMENT (doctor_id, appointment_date);
CREATE INDEX idx_consultation_appointment_id ON CONSULTATION_NOTE (appointment_id);
